import argparse
import os
from pathlib import Path
from shutil import copyfile
import subprocess
from typing import Union

from surfmap.bin.multival_csv_to_pdb import run as run_multival_csv2pdb



def get_args():
    parser = argparse.ArgumentParser(description="Script to compute electrostatics. Returns PDB files with coordinates of the shell surface particles and electrostatic.")

    parser.add_argument(
        "-pdb",
        required=True,
        type=str,
        help="Path to the pdbfile of the protein complex"
    )
    
    parser.add_argument(
        "-csv",
        required=True,
        type=str,
        help="CSV file with coordinates of the shell particles."    
    )

    parser.add_argument(
        "-pqr",
        required=False,
        type=str,
        default="",
        help="PQR file used to build input file of APBS"    
    )

    parser.add_argument(
        "-out",
        type=str,
        default=Path("."),
        help="Path of the output"
    )

    parser.add_argument(
        "-subdir",
        type=str,
        default=Path("tmp-elec"),
        help="Path name of the electrostatics directory content"
    )
    
    return parser.parse_args()


def edit_inputgen(inputgen_file: Union[str, Path], pqrfile: Union[str, Path]):
    with open(inputgen_file, 'r') as _file :
        data = _file.read()

    # Replace some data
    data = data.replace(Path(pqrfile).name, pqrfile)
    data = data.replace("pot dx pot", f"pot dx {pqrfile}")

    # Write the file out
    with open(inputgen_file, 'w') as _file:
        _file.write(data)


def run(pdb_filename: Union[str, Path], csv_filename: Union[str, Path], pqr_filename: Union[str, Path]="", out_dir: Union[str, Path]=".", out_subdir: Union[str, Path]="tmp-elec"):
    
    # define access to useful APBS executables
    PATH_APBS = Path(os.getenv("APBS"))
    apbs = f"{str(PATH_APBS / 'bin' / 'apbs')}"
    inputgen = f"{str(PATH_APBS)}/share/apbs/tools/manip/inputgen.py"
    multivalue = f"{str(PATH_APBS)}/share/apbs/tools/bin/multivalue"

    # Create directory containing electrostatics calculation related files
    outdir = Path(out_dir) / Path(out_subdir)
    outdir.mkdir(exist_ok=True, parents=True)
    outfile_basename = str(outdir / Path(pdb_filename).stem)

    # compute pqr file if not given as input
    outfile_pqr = f"{outfile_basename}.pqr"
    if not pqr_filename:
        cmd_pdb2pqr = ["pdb2pqr30", "--ff", "CHARMM", "--whitespace", pdb_filename, outfile_pqr]
        # print(f"  - Running pdb2pqr")
        completed_process = subprocess.run(cmd_pdb2pqr, capture_output=True)
    else:
        copyfile(src=pqr_filename, dst=outfile_pqr)

    # generate APBS input file
    outfile_in = f"{outfile_basename}.in"  # automaticall generated in the same path as the pqr file
    cmd_inputgen = ["python3", inputgen, "--method=auto", outfile_pqr]
    # print(f"  - Running inputgen")
    completed_process = subprocess.run(args=cmd_inputgen, capture_output=True)
    # edit inputgen outfile
    # print(f"  - Editing APBS input")
    edit_inputgen(inputgen_file=outfile_in, pqrfile=outfile_pqr)

    # compute APBS electrostatics calculation
    outfile_pot = f"{outfile_pqr}.dx"  # default output name of APBS
    cmd_apbs = [apbs, outfile_in]
    # print(f"  - Running APBS")
    completed_process = subprocess.run(args=cmd_apbs, capture_output=True)

    # cross the MSMS generated CSV file with the potential gridfile created by APBS
    outfile_multivalue = f"{outfile_basename}.mult"
    cmd_multivalue = [multivalue, csv_filename, outfile_pot, outfile_multivalue]
    # print(f"  - Running multivalue")
    completed_process = subprocess.run(args=cmd_multivalue, capture_output=True)

    # convert .csv file into a PDB file
    outfile_pdb = f"{outfile_basename}_shell.pdb"
    # print(f"  - Running csv2pdb")
    run_multival_csv2pdb(ifile=outfile_multivalue, ofile=outfile_pdb)

    # remove io.mc generated by APBS
    io_apbs = Path.cwd() / "io.mc"
    io_apbs.unlink(missing_ok=True)

    return outfile_pdb


def main():
    args = get_args()

    return run(
        pdb_filename=args.pdb,
        csv_filename=args.csv,
        pqr_filename=args.pqr,
        out_dir=args.out,
        out_subdir=args.subdir
    )

    
